-- This comment exists only so that you can edit it if you want to run this GitHub
-- action by pushing a trivial commit.

name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        stack update
        stack install --only-dependencies
    - name: Build
      run: |
        stack build
    - name: Run tests
      run: stack test
